### ISSUE TITLE
Frontend for SysY

### ISSUE THREAD

**Issue by JuniMay** [JuniMay/orzcc#11]

**Comment by FlandreScarlet36** [comment]
Ref: https://github.com/pku-minic/kira-rs/tree/master?tab=readme-ov-file
https://github.com/lalrpop/lalrpop/tree/master

**Comment by fscdc** [comment]
add some ref:
https://gitlab.eduxiji.net/educg-group-17291-1894922/202310614201204-3168
https://gitlab.eduxiji.net/educg-group-17291-1894922/202310013201098-3687
https://gitlab.eduxiji.net/202310146201457/compiler2023-yetjustsysyc

**Comment by fscdc** [comment]
Ref for lalrpop
https://github.com/lalrpop/lalrpop

**Comment by fscdc** [comment]
TODO：
1. distinguish constexp & exp
2. cmd for frontend(supplement)
3. process Hex floating-point

**Comment by fscdc** [comment]
TODO2：
STRUCT
